version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://crud.ct0mwwiqy26q.us-east-1.rds.amazonaws.com:3306/crud?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3309:3309
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: root
      MYSQL_PASSWORD: Srik@nth12345
      MYSQL_ROOT_PASSWORD: Srik@nth12345
networks:
  springapimysql-net: